"""Software-only 20-case stress evidence sheet and PNG heatmap.

A test certificate from this module is NOT ISRO-issued certification.
"""
from pathlib import Path

def write_stress_pdf(path,result):
    cases=result.get('cases',[])
    if not cases:raise ValueError('Stress cases missing')
    ops=[]
    def label(x,y,text,size=10,color=(.80,.88,.91)):
        safe=str(text).encode('ascii','replace').decode('ascii').replace('\\','\\\\').replace('(','\\(').replace(')','\\)')
        ops.append(f'BT /F1 {size} Tf {color[0]} {color[1]} {color[2]} rg {x} {y} Td ({safe}) Tj ET')
    ops.append('.04 .09 .14 rg 0 0 612 792 re f')
    label(40,757,'V-CAPAT PRO   /   20-CASE SOFTWARE STRESS EVIDENCE',15,(.45,.9,.75))
    label(40,732,'NOT AN ISRO-ISSUED OR HARDWARE QUALIFICATION CERTIFICATE',10,(1,.72,.49))
    label(40,711,'Seeded short-duration cases. N/A checks are not passes.',9)
    label(40,684,'CASE                                 ERROR PX     LOSS %    PASS / FAIL',9,(.52,.72,.8))
    y=663
    for i,c in enumerate(cases[:20]):
        ops.append(('.075 .15 .19' if i%2==0 else '.055 .12 .17')+f' rg 36 {y-8} 540 24 re f')
        label(43,y,str(c.get('name',f'case {i+1}'))[:35],8)
        label(324,y,str(c.get('pointing_rmse_px','N/A')),8)
        label(403,y,str(c.get('target_loss_pct','N/A')),8)
        label(483,y,f"{c.get('passed_checks',0)} / {c.get('failed_checks',0)}",8)
        y-=27
    label(40,101,f"Cases without FAIL checks: {result.get('passing_cases',0)}/{len(cases)} (N/A remains unresolved)",10,(.45,.9,.75))
    label(40,78,'Stress cases are illustrative short tests. Verify on controlled test equipment.',9)
    label(40,56,'Generated by V-CAPAT PRO / NOT OFFICIAL CERTIFICATION',9,(1,.72,.49))
    stream=('\n'.join(ops)+'\n').encode('ascii')
    objects=[b'<< /Type /Catalog /Pages 2 0 R >>',b'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
             b'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
             b'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
             b'<< /Length '+str(len(stream)).encode()+b' >>\nstream\n'+stream+b'endstream']
    output=bytearray(b'%PDF-1.4\n');positions=[0]
    for i,obj in enumerate(objects,1):
        positions.append(len(output));output+=f'{i} 0 obj\n'.encode()+obj+b'\nendobj\n'
    offset=len(output);output+=f'xref\n0 {len(objects)+1}\n0000000000 65535 f \n'.encode()
    for n in positions[1:]:output+=f'{n:010d} 00000 n \n'.encode()
    output+=f'trailer\n<< /Size {len(objects)+1} /Root 1 0 R >>\nstartxref\n{offset}\n%%EOF\n'.encode()
    Path(path).write_bytes(output)
    return Path(path)


def write_stress_heatmap(path,result):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    rows=sorted(set(c['atmosphere'] for c in result['cases']))
    cols=sorted(set(c['trajectory'] for c in result['cases']))
    values=[[next((c['failed_checks'] for c in result['cases'] if c['atmosphere']==row and c['trajectory']==col),0) for col in cols] for row in rows]
    fig,ax=plt.subplots(figsize=(8,4.7));im=ax.imshow(values,cmap='YlOrRd',vmin=0,vmax=5)
    ax.set_xticks(range(len(cols)),cols);ax.set_yticks(range(len(rows)),rows)
    for i,row in enumerate(values):
        for j,value in enumerate(row):ax.text(j,i,str(value),ha='center',va='center',color='black')
    ax.set_title('Failed requirements by scenario · N/A separate from pass')
    fig.colorbar(im,ax=ax,label='Failed checks');fig.tight_layout();fig.savefig(path,dpi=125);plt.close(fig)
    return Path(path)
