"""Verify a built Windows executable and the release package around it."""
from __future__ import annotations
import argparse
import json
import subprocess
import sys
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('exe')
    ap.add_argument('--output', default='build/release_smoke')
    args = ap.parse_args()
    exe = Path(args.exe).resolve()
    if not exe.is_file() or exe.stat().st_size < 100_000:
        print('FAIL: executable missing or unexpectedly small:', exe)
        return 2
    out = Path(args.output).resolve()
    out.mkdir(parents=True, exist_ok=True)
    cmd = [str(exe), '--self-test', '--output', str(out)]
    print('Running:', ' '.join(cmd))
    completed = subprocess.run(cmd, timeout=120)
    if completed.returncode:
        print('FAIL: packaged self-test returned', completed.returncode)
        return completed.returncode
    summaries = sorted(out.rglob('summary.json'))
    if not summaries:
        print('FAIL: no summary.json generated by packaged self-test')
        return 3
    data = json.loads(summaries[-1].read_text(encoding='utf-8'))
    if int(data.get('processed_frames', 0)) < 30:
        print('FAIL: insufficient processed frames in packaged self-test')
        return 4
    print('PASS: executable launched, bundled resources loaded, pipeline ran, and evidence exported.')
    print('Summary:', summaries[-1])
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
