"""Physical constants and explicit ISRO evaluation thresholds."""
LIGHT_SPEED_M_S=299_792_458.0
ACQUISITION_LIMIT_S=2.0
TRACKING_ERROR_LIMIT_PX=10.0
TARGET_LOSS_LIMIT_PCT=5.0
REACQUISITION_LIMIT_S=1.0
MIN_PROCESSING_FPS=20.0
